[workspace]
resolver = "2"

members = [
    "crates/kpe-schema",
    "crates/kpe-parametric",
    "crates/kpe-geometry",
    "crates/kpe-fabrication",
    "crates/kpe-material",
    "crates/kpe-wasm",
    "crates/kpe-cli",
    "apps/desktop",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
glam = "0.29"
thiserror = "2"
wasm-bindgen = "0.2"
criterion = { version = "0.5", features = ["html_reports"] }

[patch.crates-io]
core2 = { git = "https://github.com/bbqsrc/core2", rev = "545e84bcb0f235b12e21351e0c69767958efe2a7" }

# Optimizado para minimizar espacio en disco
# strip elimina debug symbols (los .pdb son los que más pesan en Windows)
# incremental=false evita que la carpeta incremental se acumule
[profile.dev]
strip = "debuginfo"
debug = 0
incremental = false

# Las dependencias externas se optimizan a velocidad máxima
[profile.dev.package."*"]
opt-level = 3
debug = 0

# kpe-app se compila rápido para iterar
[profile.dev.package.kpe-app]
opt-level = 0
debug = 0
