pub mod brep;
pub mod csg;
pub mod transform;
pub mod joint;
pub mod mesh;
pub mod sketch;
pub mod extrude;
pub mod predicates;
pub mod intersection;
pub mod bvh;
pub mod classify;
pub mod stitch;
pub mod split;
pub mod push_pull;

pub use brep::BRepKernel;
pub use csg::CsgKernel;
pub use transform::TransformEngine;
pub use joint::JointEngine;
pub use mesh::MeshBuilder;
pub use mesh::build_mesh_from_node;
pub use sketch::SketchEngine;
pub use sketch::SketchDocument;
pub use sketch::triangulate_contour;
pub use sketch::entities::{Point, Line, Arc, Circle, EntityId};
pub use sketch::constraints::Constraint;
pub use sketch::solver::Solver;
pub use sketch::inference::{InferenceEngine, SnapResult};
pub use push_pull::extrude_face;
pub use predicates::*;
pub use intersection::triangle_triangle_intersection;
pub use bvh::BVH;
pub use classify::classify_point_against_mesh;
pub use stitch::Stitcher;
